CREATE TABLE IF NOT EXISTS categorie_document (
    id_categorie SERIAL PRIMARY KEY,
    id_type INTEGER NOT NULL REFERENCES type_prestataire(id_type) ON DELETE CASCADE,
    nom_categorie VARCHAR(100) NOT NULL
);

INSERT INTO categorie_document (id_type, nom_categorie) VALUES
(1, 'Diplôme de médecine'),
(1, 'Numéro RPPS'),
(1, 'Ordre des médecins'),
(1, 'Assurance responsabilité civile'),
(2, 'Diplôme d''État infirmier'),
(2, 'Numéro RPPS'), 
(2, 'Assurance responsabilité civile'),
(3, 'Diplôme de kinésithérapie'),
(3, 'Numéro RPPS'),
(3, 'Assurance responsabilité civile'),
(4, 'Diplôme ADVF ou équivalent'),
(4, 'Casier judiciaire'),
(4, 'Assurance responsabilité civile'),
(5, 'BAFA ou équivalent'),
(5, 'Casier judiciaire'),
(5, 'Assurance responsabilité civile'),
(6, 'Certification professionnelle'),
(6, 'Assurance responsabilité civile'),
(7, 'CAP Cuisine ou équivalent'),
(7, 'Certificat hygiène alimentaire'),
(7, 'Assurance responsabilité civile'),
(8, 'BPJEPS ou équivalent'),
(8, 'Casier judiciaire'),
(8, 'Assurance responsabilité civile'),
(9, 'Diplôme informatique'),
(9, 'Assurance responsabilité civile'),
(10, 'Permis de conduire'),
(10, 'Carte professionnelle VTC'),
(10, 'Assurance véhicule'),
(11, 'Certification animalière'),
(11, 'Assurance responsabilité civile'),
(12, 'Portfolio'),
(12, 'Assurance responsabilité civile'),
(13, 'Diplôme comptabilité'),
(13, 'Assurance responsabilité civile'),
(14, 'Certificat du barreau'),
(14, 'Assurance responsabilité civile'),
(15, 'Pièce d''identité'),
(15, 'Assurance responsabilité civile')
ON CONFLICT DO NOTHING;