services:
  silver-app:
    image: php:8.2-apache
    container_name: silver_happy_apache
    ports:
      - "8080:80"
    volumes:
      - ./app-php:/var/www/html
    restart: always
    depends_on:
      - silver-db
      - silver-go

  silver-go:
    build: ./api-go
    container_name: silver_happy_go
    env_file:
      - .env
    ports:
      - "8082:8081"
    restart: always
    depends_on:
      - silver-db

  silver-db:
    image: postgres:16-alpine
    container_name: silver_happy_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  silver-pgadmin:
    image: dpage/pgadmin4
    container_name: silver_happy_pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@silverhappy.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - silver-db

volumes:
  db_data:
