services:
  silver-app:
    image: php:8.2-apache
    container_name: silver_happy_apache
    ports:
      - "8080:80"
    volumes:
      - ./app-php:/var/www/html
    restart: always
    depends_on:
      - silver-db
      - silver-go
    networks:
      - silver-net

  silver-go:
    build: ./api-go
    container_name: silver_happy_go
    env_file:
      - .env
    ports:
<<<<<<< HEAD
      - "8081:8081"
=======
      - "8082:8081"
>>>>>>> origin/zak
    restart: always
    depends_on:
      - silver-db
    networks:
      - silver-net
<<<<<<< HEAD
    volumes:
      - ./uploads:/app/uploads
=======
>>>>>>> origin/zak

  silver-db:
    image: postgres:16-alpine
    container_name: silver_happy_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - silver-net

  silver-pgadmin:
    image: dpage/pgadmin4
    container_name: silver_happy_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@silverhappy.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - silver-db
    networks:
      - silver-net

networks:
  silver-net:
    driver: bridge

volumes:
  db_data:
  pgadmin_data:
